[[redirects]]
  from = "/pdf"
  to = "/Sidney Alcantara Resume.pdf"
  status = 301

[[redirects]]
  from = "/fonts/*"
  to = "https://fonts-sidney-me.netlify.app/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/pa/*"
  to = "https://plausible.io/:splat"
  status = 200

[[edge_functions]]
  path = "/fonts/*"
  function = "rewrite-pass-headers"
